-- Competition Fantasy v2 baseline schema (format-first).
-- Conventions: plural table names, bigint identity ids, `key` = stable slug used by JSON imports.

create table universes (
    id            bigint generated by default as identity primary key,
    key           varchar(64)  not null unique,
    name          varchar(120) not null,
    description   text,
    type          varchar(16)  not null default 'FICTIONAL',   -- FICTIONAL | REAL
    uses_nations  boolean      not null default false,
    created_at    timestamptz  not null default now(),
    updated_at    timestamptz  not null default now()
);

create table nations (
    id            bigint generated by default as identity primary key,
    universe_id   bigint       not null references universes(id) on delete cascade,
    key           varchar(64)  not null,
    name          varchar(120) not null,
    code          varchar(3)   not null,
    colors        jsonb,                                         -- {"primary":"#..","secondary":"#..","text":"#.."}
    description   text,
    unique (universe_id, key),
    unique (universe_id, code)
);

create table stadiums (
    id            bigint generated by default as identity primary key,
    universe_id   bigint       not null references universes(id) on delete cascade,
    key           varchar(64)  not null,
    name          varchar(120) not null,
    city          varchar(120),
    capacity      integer,
    inspired_by   varchar(160),
    description   text,
    unique (universe_id, key)
);

create table teams (
    id               bigint generated by default as identity primary key,
    universe_id      bigint       not null references universes(id) on delete cascade,
    nation_id        bigint       references nations(id) on delete set null,
    type             varchar(16)  not null,                      -- CLUB | NATIONAL
    key              varchar(64)  not null,
    name             varchar(120) not null,
    short_name       varchar(40),
    code             varchar(4),
    home_stadium_id  bigint       references stadiums(id) on delete set null,
    description      text,
    founded_year     integer,
    dissolved_year   integer,
    unique (universe_id, key)
);
create index ix_teams_universe_name on teams (universe_id, lower(name));

create table team_aliases (
    id        bigint generated by default as identity primary key,
    team_id   bigint       not null references teams(id) on delete cascade,
    alias     varchar(120) not null,
    unique (team_id, alias)
);
create index ix_team_aliases_lower on team_aliases (lower(alias));

create table team_profiles (
    id            bigint generated by default as identity primary key,
    team_id       bigint       not null references teams(id) on delete cascade,
    year          integer      not null,
    display_name  varchar(120),
    sponsor       varchar(120),
    colors        jsonb,                                         -- {"home":{"bg":"#","text":"#"},"away":{...}}
    notes         text,
    unique (team_id, year)
);

create table kits (
    id              bigint generated by default as identity primary key,
    team_id         bigint       not null references teams(id) on delete cascade,
    year            integer      not null,
    kind            varchar(8)   not null,                       -- HOME | AWAY | THIRD
    shirt_color     varchar(32),
    shorts_color    varchar(32),
    socks_color     varchar(32),
    sponsor         varchar(120),
    image_asset_id  bigint,
    unique (team_id, year, kind)
);

create table competitions (
    id            bigint generated by default as identity primary key,
    universe_id   bigint       not null references universes(id) on delete cascade,
    key           varchar(64)  not null,
    name          varchar(120) not null,
    sport         varchar(32)  not null default 'FOOTBALL',
    team_level    varchar(16)  not null default 'CLUB',          -- CLUB | NATIONAL
    tier          integer,
    description   text,
    unique (universe_id, key)
);

create table format_presets (
    id          bigint generated by default as identity primary key,
    key         varchar(64)  not null unique,
    name        varchar(120) not null,
    family      varchar(64),
    definition  jsonb        not null,
    builtin     boolean      not null default false,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

create table seasons (
    id              bigint generated by default as identity primary key,
    competition_id  bigint       not null references competitions(id) on delete cascade,
    key             varchar(64)  not null,
    name            varchar(120) not null,
    year            integer,
    start_date      date,
    end_date        date,
    status          varchar(16)  not null default 'PLANNED',     -- PLANNED | ONGOING | COMPLETED
    preset_key      varchar(64),
    format          jsonb        not null,                       -- resolved copy of the format definition
    notes           text,
    unique (competition_id, key)
);

create table season_teams (
    id         bigint generated by default as identity primary key,
    season_id  bigint  not null references seasons(id) on delete cascade,
    team_id    bigint  not null references teams(id) on delete cascade,
    seed       integer,
    pot        integer,
    unique (season_id, team_id)
);

create table stages (
    id         bigint generated by default as identity primary key,
    season_id  bigint       not null references seasons(id) on delete cascade,
    ordinal    integer      not null,
    key        varchar(32)  not null,
    name       varchar(120) not null,
    type       varchar(16)  not null,                            -- ROUND_ROBIN | KNOCKOUT | LEAGUE_PHASE | SINGLE_MATCH
    config     jsonb,                                            -- the stage's definition from the format
    unique (season_id, key)
);

create table stage_groups (
    id        bigint generated by default as identity primary key,
    stage_id  bigint       not null references stages(id) on delete cascade,
    ordinal   integer      not null,
    key       varchar(32)  not null,
    name      varchar(120) not null,
    unique (stage_id, key)
);

create table stage_group_teams (
    id              bigint generated by default as identity primary key,
    stage_group_id  bigint  not null references stage_groups(id) on delete cascade,
    team_id         bigint  references teams(id) on delete cascade,        -- null until the slot is resolved
    entry_source    jsonb,                                                -- e.g. {"type":"GROUP_POSITION","stage":"GS","group":"A","position":2}
    position        integer not null default 0,
    unique (stage_group_id, team_id)
);

create table rounds (
    id              bigint generated by default as identity primary key,
    stage_group_id  bigint       not null references stage_groups(id) on delete cascade,
    number          integer      not null,
    name            varchar(60),
    start_date      date,
    end_date        date,
    unique (stage_group_id, number)
);

create table ko_rounds (
    id         bigint generated by default as identity primary key,
    stage_id   bigint       not null references stages(id) on delete cascade,
    ordinal    integer      not null,
    key        varchar(32)  not null,
    name       varchar(120) not null,
    legs       integer      not null default 1,
    placement  boolean      not null default false,
    unique (stage_id, key)
);

create table ties (
    id              bigint generated by default as identity primary key,
    ko_round_id     bigint      not null references ko_rounds(id) on delete cascade,
    position        integer     not null,
    home_source     jsonb,
    away_source     jsonb,
    home_team_id    bigint      references teams(id) on delete set null,
    away_team_id    bigint      references teams(id) on delete set null,
    winner_team_id  bigint      references teams(id) on delete set null,
    resolution      varchar(16),                                          -- AGGREGATE | AWAY_GOALS | EXTRA_TIME | PENALTIES | REPLAY | WALKOVER | LOTS
    unique (ko_round_id, position)
);

create table matches (
    id              bigint generated by default as identity primary key,
    season_id       bigint      not null references seasons(id) on delete cascade,
    stage_id        bigint      not null references stages(id) on delete cascade,
    round_id        bigint      references rounds(id) on delete cascade,
    tie_id          bigint      references ties(id) on delete cascade,
    leg             integer     not null default 1,
    home_team_id    bigint      references teams(id) on delete set null,
    away_team_id    bigint      references teams(id) on delete set null,
    match_date      date,
    stadium_id      bigint      references stadiums(id) on delete set null,
    status          varchar(16) not null default 'SCHEDULED',            -- SCHEDULED | PLAYED | UNKNOWN | CANCELLED
    home_score      integer,
    away_score      integer,
    home_et         integer,                                              -- score after extra time (total)
    away_et         integer,
    home_pens       integer,
    away_pens       integer,
    walkover        varchar(4),                                           -- HOME | AWAY (side awarded the match)
    winner_team_id  bigint      references teams(id) on delete set null,
    source          varchar(16) not null default 'MANUAL',               -- NOTEBOOK | MANUAL | IMPORT | SIMULATED
    source_ref      varchar(160),
    confidence      varchar(16) not null default 'VERIFIED',             -- DRAFT | VERIFIED
    notes           text,
    check (round_id is not null or tie_id is not null)
);
create index ix_matches_round on matches (round_id);
create index ix_matches_tie on matches (tie_id);
create index ix_matches_season on matches (season_id);
create index ix_matches_teams on matches (home_team_id, away_team_id);

create table standings (
    id                bigint generated by default as identity primary key,
    stage_group_id    bigint      not null references stage_groups(id) on delete cascade,
    type              varchar(16) not null,                              -- CALCULATED | RECORDED
    checkpoint_round  integer     not null default 0,                    -- 0 = final / current
    computed_at       timestamptz not null default now(),
    unique (stage_group_id, type, checkpoint_round)
);

create table standing_rows (
    id             bigint generated by default as identity primary key,
    standing_id    bigint  not null references standings(id) on delete cascade,
    team_id        bigint  not null references teams(id) on delete cascade,
    position       integer not null,
    played         integer not null default 0,
    won            integer not null default 0,
    drawn          integer not null default 0,
    lost           integer not null default 0,
    goals_for      integer not null default 0,
    goals_against  integer not null default 0,
    goal_diff      integer not null default 0,
    points         integer not null default 0,
    adjustment     integer not null default 0,
    zone           varchar(32),
    tie_note       varchar(160),
    unique (standing_id, team_id)
);

create table honours (
    id         bigint generated by default as identity primary key,
    season_id  bigint      not null references seasons(id) on delete cascade,
    team_id    bigint      not null references teams(id) on delete cascade,
    kind       varchar(32) not null,                                     -- CHAMPION | RUNNER_UP | THIRD | FOURTH | PROMOTED | RELEGATED
    manual     boolean     not null default true,
    unique (season_id, kind, team_id)
);

create table assets (
    id            bigint generated by default as identity primary key,
    storage_key   varchar(255) not null unique,
    url           varchar(512) not null,
    content_type  varchar(80),
    size_bytes    bigint,
    width         integer,
    height        integer,
    title         varchar(160),
    collection    varchar(120),
    tags          jsonb,
    created_at    timestamptz  not null default now()
);

create table asset_slots (
    id          bigint generated by default as identity primary key,
    owner_type  varchar(32) not null,                                    -- UNIVERSE | NATION | TEAM | KIT | STADIUM | COMPETITION | SEASON | WEB
    owner_id    bigint      not null,
    slot        varchar(32) not null,                                    -- LOGO | BANNER | FLAG | EMBLEM | AVATAR | IMAGE | POSTER | BACKGROUND
    asset_id    bigint      not null references assets(id) on delete cascade,
    current     boolean     not null default true,
    created_at  timestamptz not null default now()
);
create index ix_asset_slots_owner on asset_slots (owner_type, owner_id, slot);

create table import_runs (
    id           bigint generated by default as identity primary key,
    file_name    varchar(255) not null,
    source       varchar(16)  not null,                                  -- REPO | UPLOAD
    checksum     varchar(64),
    dry_run      boolean      not null default false,
    status       varchar(16)  not null,                                  -- RUNNING | SUCCESS | FAILED | REVERTED
    started_at   timestamptz  not null default now(),
    finished_at  timestamptz,
    summary      jsonb,
    log          text
);

create table import_changes (
    id           bigint generated by default as identity primary key,
    run_id       bigint      not null references import_runs(id) on delete cascade,
    ordinal      integer     not null,
    entity_type  varchar(32) not null,
    entity_id    bigint      not null,
    action       varchar(16) not null                                   -- CREATED | UPDATED | REPLACED
);
create index ix_import_changes_run on import_changes (run_id);
