spring.application.name=competition-api
server.port=${PORT:8080}

# JPA
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.open-in-view=true

# Flyway
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration
