ALTER TABLE teams ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS banner_media_id UUID REFERENCES media_files(id) ON DELETE SET NULL;
ALTER TABLE teams ADD COLUMN IF NOT EXISTS banner_url VARCHAR(1000);
