ALTER TABLE nations ADD COLUMN IF NOT EXISTS description TEXT;
ALTER TABLE nations ADD COLUMN IF NOT EXISTS logo_url VARCHAR(1000);
ALTER TABLE nations ADD COLUMN IF NOT EXISTS logo_media_id UUID REFERENCES media_files(id) ON DELETE SET NULL;
ALTER TABLE nations ADD COLUMN IF NOT EXISTS banner_url VARCHAR(1000);
ALTER TABLE nations ADD COLUMN IF NOT EXISTS banner_media_id UUID REFERENCES media_files(id) ON DELETE SET NULL;
